### ISSUE TITLE
Mounted Units + blitz

### ISSUE THREAD

**Issue by qqqbbb** [Thalassicus/cep-bnw#123] opened 2014-01-07 20:37 UTC
Mounted Units with blitz promotion spend 3 MP on first attack regardless of terrain.

**Comment by stackpoint** [comment] 2014-01-09 05:55
If I remember correctly, this was done to barbarian chariots to lower their MP to 1 after their attack. Not sure if this was intended for other units but I can't locate the code that does this at the moment.

**Comment by stackpoint** [comment] 2014-01-09 23:49
It looks like the promotion, PROMOTION_CAN_MOVE_AFTER_ATTACKING, has not been reactivated yet. I'm not sure if I should disable the blitz lua code for now or attempt to reactivate the promotion.

**Comment by stackpoint** [comment] 2014-01-12 23:31
This should be fixed here: https://github.com/Thalassicus/cep-bnw/commit/b67aadfe529e6abd678274cb06521135bf5928ac

**Closed as completed by stackpoint** 2014-01-12 23:31 UTC
Labels: bug
