### ISSUE TITLE
GA still generates +1 Gold on every gold-producing tile

### ISSUE THREAD

**Issue by bernd-das-brot** [Thalassicus/cep-bnw#104] opened 2014-01-01 21:27 UTC
(3.12.1) Golden Ages still generate +1 gold on every gold-producing tile. I posted this two weeks ago and the issue was closed very quickly, but it's still present. Or is this intended?

**Comment by stackpoint** [comment] 2014-01-03 22:42
Is this a text error or a gameplay error? Is the gold actually being generated or is it just saying that it is?

**Comment by bernd-das-brot** [comment] 2014-01-03 22:54
Think it is a gameplay error! At least in the cityscreen and on the map every tile producing gold produces one more while the GA is ongoing. And the loss of income after the GA seemed more than a 20% modifier.

**Comment by stackpoint** [comment] 2014-01-10 01:00
Actually, I don't know if this behavior is intended or not. Could you point me to documentation or forum posts that states that GAs aren't supposed to generate +1 gold? Was this the behavior in GEM?

**Comment by clapbr** [comment] 2014-01-15 11:58
IMO it´s implied you should get the 20% instead of +1 per gold tile but only Thala may know.

**Comment by skodkim** [comment] 2014-01-15 16:26
I think its a bug (haven't tested it yet) but if it is true it's kind of weirds cause as far as I can tell it's been removed in the file Cities\CEC_Data.xml:

```
    <Update>
        <Where Type="YIELD_GOLD" />
        <Set MinPlayer="11"
             MinCity="0"
             GoldenAgeYieldMod="20"
             GoldenAgeYield="0"
             GoldenAgeYieldThreshold="0"
             AIWeightPercent="100"
             />
    </Update>
```

Edit: Just tested and its true: every gold producing tile produce +1 goild during the GA.

\Skodkim

**Comment by clapbr** [comment] 2014-01-15 17:09
So what´s the final word on intended behavior?

**Comment by stackpoint** [comment] 2014-01-15 17:35
@skodkim, It looks like that section of code is commented out for some reason but it implies that the gold shouldn't be there.

@clapbr, I can't say since I don't work with the game balance portion of this mod for the most part. But it looks likely that you're right. We should know once @Thalassicus pops in.

**Comment by skodkim** [comment] 2014-01-15 19:03
@stackpoint I'm pretty sure this is a bug as the text differs. I didn't notice that the entire goldenage section was commented out. Unless you or someone else strongly disagrees I'm going to commit a fix for this in the next version (Thal can reject it if he wants to).

\Skodkim

**Comment by stackpoint** [comment] 2014-01-21 00:00
This should be fixed here: https://github.com/Thalassicus/cep-bnw/commit/9b17f501aaa98a2017e007b92a4e093147010a2f

**Closed as completed by stackpoint** 2014-01-21 00:00 UTC
Labels: bug
