### ISSUE TITLE
Barbarians

### ISSUE THREAD

**Issue by Thalassicus** [Thalassicus/cep-bnw#96] opened 2013-12-27 23:52 UTC
Barbarian camps don't appear. This is a very puzzling issue I've been trying to figure out for two days.

**Comment by skodkim** [comment] 2013-12-28 05:45
It worked in 3.10.2 (haven't played 3.11 because of an error in database.log).

The only tweak to barbarians I can see since then is tjis: https://github.com/Thalassicus/cep-bnw/blob/226e786c7bd1e4c72990179222a895a16fa20983/Cat/Cat/AI/CEAI_FixTables.lua

Could that be the cause (even though the changes seem valid except the now fixed syntax error)?

\Skodkim

**Comment by GrantSP** [comment] 2013-12-28 05:50
I can't reproduce the error with only CAT loaded. It appears to be in CEG.

**Comment by GrantSP** [comment] 2013-12-28 19:48
While it is true I can't get the error to appear when CEG isn't loaded, I guess it is also possible a value set up in CAT may only be used IF CEG is loaded. So, the assertion it isn't in CAT may be premature. Or to put it anothe way, wrong!

**Comment by ghost** [comment] 2013-12-28 21:31
I have found the culprit! Cat/Cat/AI/CEAI_Worlds.xml

This was a new file introduced in 3.11.1, if you delete this file barb camps appear using 3.11.3.

**Comment by Thalassicus** [comment] 2013-12-28 21:55
I think I fixed the problem.

The Worlds table had incorrect decimal numbers for FogTilesPerBarbarianCamp, which can only accept integers. This table is set in /Cat/AI/CEAI_Worlds.xml. I added the file in v3.11.1. I changed that field to the intended integers and barbarian camps seem to appear normally.

**Comment by ghost** [comment] 2013-12-28 22:03
I see you found it Thal!  Keep up the good work!

**Comment by GrantSP** [comment] 2013-12-28 22:05
Just why are our values for this tag so different to vanilla values?
WORLDSIZE_DUEL is 13 in vanilla but 0.81 in CEG.

Are we looking at how this value is used incorrectly?

**Comment by GrantSP** [comment] 2013-12-28 22:24
Please feel at home to call me an idiot if wrong.
The value is simply the number of tiles that are not "seen" by ANY player? Yes?
This would include AI players?
Are these tiles contiguous?
Why were values with decimals working in GEM but not now?

**Comment by GrantSP** [comment] 2013-12-28 22:31
GEM set these values to 25% of vanilla. Are we really doing such a job on barbarians to have such a drastic change?

**Comment by GrantSP** [comment] 2013-12-28 23:45
Ok so the new version has these values changed. But why are they different on CEAI_FixTables.lua and CEAI_Worlds.xml?
5 in the lua and 20 in the xml. Now changed to 10 in the xml.

**Comment by Thalassicus** [comment] 2013-12-29 00:12
The lua and xml files are intended to match.

The lua file's used by other lua files, while the data file is used by c++ files in the game core. The separate files exist because of a bug in the way the game loads data.

The unmodded game changes the tiles per player on different map sizes. This causes serious balance issues, like players unable to use trade routes on large/huge maps, where players are too far apart. CEP uses a consistent tiles-per-player ratio for all map sizes. This means things like FogTilesPerBarbarianCamp (or trade route lengths) don't need to change for different map sizes.

The unmodded game also lets barb camps stop spawning after the ancient era. This happens because the number of tiles where camps can spawn are more numerous than the number of camps that can actually spawn. 

Imagine a chessboard with 16 pawns placed on random tiles. If you continually move pawns from the center area to new random places on the board, the center will eventually have no pawns. This is what happens in the unmodded game with barb camps near players. All the camps eventually shift to areas players can't reach until the very late game (like islands in the Pacific Ocean). Barbarians are insignificant by the time we can actually reach those camps.

In CEP, camps continue spawning until the fog is full, limited by the minimum distance requirements between camps.

**Comment by Thalassicus** [comment] 2013-12-29 00:15
Anyone please close this issue if you can confirm barbarian camps are appearing in version 1.12 or later.

**Comment by GrantSP** [comment] 2013-12-29 00:19
I can confirm the existence of barbarians but I am still none the wiser as to why the xml and lua are different.
The xml is 10 and the lua is 5 and to further confuse the issue the database shows a value of 3 once everything is loaded

**Comment by GrantSP** [comment] 2013-12-29 01:12
The appearance of the camps might be fixed but I think we might need to look closer at the frequency of unit spawn and more importantly the type of units that appear.

There are barbarian Pirates, Biremes, Axmen, Composite Bowmen and Spearmen all over the map.

I can clear a camp ok but I can find another camp just on the other side of the mountain on the way back to my city.
With all the naval units along the coast it makes it very hard to scout the land with just a scout.

**Comment by stackpoint** [comment] 2014-01-10 00:39
Discussion on barbarian unit composition should probably take place in the forums. Let me know if you feel otherwise.

**Closed as completed by stackpoint** 2014-01-10 00:39 UTC
Labels: bug, gameplay
