### ISSUE TITLE
Indexing Bugs (Worlds, GameSpeeds, HandicapInfos)

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#201] opened 2014-02-28 14:05 UTC
(formerly IGE incompatible with New Features Build)
Hi

I know it isn't an official build but when testing the New Features Build I get the following error from IGE (Ingame Editor):

![civ5screen0027](https://f.cloud.github.com/assets/6018459/2294425/4b7aeb38-a081-11e3-8176-12e73cca5a28.jpg)

Any ideas?

**Comment by skodkim** [comment] 2014-02-28 15:38
Without other mods than CEG I also get errors in lua.log.

Started new game ->founded city->opened tech tree->went to city view->opened production queue->quit game

![lua log](https://f.cloud.github.com/assets/6018459/2295298/37ee6ec0-a08e-11e3-88c6-34994264ed7f.jpg)

**Comment by GrantSP** [comment] 2014-02-28 21:47
Ok I'm going to try my sleuthing here.

**YieldLibrary.lua** line has the **attempt to index field '?' (a nil value)** error, that means we haven't defined something.
**CEAI_Events.lua** line 786 has an error related to _speedinfo_
**MT_Misc.lua** has the function _Game.GetSpeedYieldMod(yieldID)_
It has no references to either **YieldTypes.YIELD_CS_MILITARY** or **YieldTypes.YIELD_CS_GREAT_PEOPLE**

I am **guessing** they will need to be added in to the function.

I really hope I am at least 30% right, that would be an improvement. :smiley:

**Comment by stackpoint** [comment] 2014-02-28 23:14
Don't worry about new-features not being officially supported since the next build will probably include it. I'll take a look.

**Comment by stackpoint** [comment] 2014-02-28 23:21
Okay, so this is probably related to a bug I caused a few builds ago regarding starting a map with a mapsize Duel. What gamespeed did you attempt to start the game with?

**Comment by GrantSP** [comment] 2014-02-28 23:26
Looks my strike-rate hasn't improved!

Back to the books for me.

**Comment by skodkim** [comment] 2014-03-01 05:27
Marathon (tiny map, deity level, pangaea map, Rome)

**Comment by stackpoint** [comment] 2014-03-01 05:36
My table copying code is causing the index 0 entries in the CepWorlds, CepHandicapInfos, and CepGameSpeeds to bug out. So right now the game options: 
- World Size: Duel
- Game Difficulty: Settler
- Game Speed: Marathon

Are currently bugged. I'm not sure why this is the case though.

**Comment by stackpoint** [comment] 2014-03-01 06:01
All other game modes aren't bugged so feel free to use them with the latest build.

**Comment by stackpoint** [comment] 2014-03-01 06:09
Okay, so the problem is that the "primary key" and "unique" aren't set (ID, Type). I don't know how to do this using SQL so I may need to just rebuild the table completely using xml.

**Comment by GrantSP** [comment] 2014-03-01 06:17
Don't give up so fast. :)
Just kidding.
I think I may have some ideas on this, let me get back home and I'll have a
crack at it..
There are a few ways to get the primary and unique keys to set. I think
Thal uses 1or2 methods to do something similar.
Have a look at the code, there may something that does what you want
already in there.

**Comment by stackpoint** [comment] 2014-03-01 06:23
Looks like SQLite doesn't support the ALTER TABLE [table_name] MODIFY ... command: http://www.sqlite.org/lang.html

Looks like I'll be doing this in xml unless you have any ideas @GrantSP. All I need to do is set the PRIMARY KEY and UNIQUE constraints to an existing table.

**Comment by stackpoint** [comment] 2014-03-01 06:26
The methods that I've seen in CEP depends on the CREATE TABLE instead of ALTER TABLE.

**Comment by GrantSP** [comment] 2014-03-01 06:33
Ahh...
There the ones I was thinking about.
That's a shame. Sql is so elegant compared xml, IMO.

**Comment by stackpoint** [comment] 2014-03-01 06:39
SQLite is missing some key functions for duplicating tables it seems.

**Comment by GrantSP** [comment] 2014-03-01 06:40
; (

**Comment by GrantSP** [comment] 2014-03-01 06:53
Just a thought as I haven't seen your code yet.
Can you DROP the existing tables and then CREATE new ones with the primary
and unique keys?

**Comment by stackpoint** [comment] 2014-03-01 07:01
I'm trying to make an exact copy of the table so I don't need to DROP the existing table. The problem is automating the copying of the columns and setting the PRIMARY KEY.

**Comment by stackpoint** [comment] 2014-03-01 08:05
Should be fixed here: https://github.com/Thalassicus/cep-bnw/commit/691900018b81815821e83e86eb03f093599bf9ad

**Closed as completed by stackpoint** 2014-03-01 08:05 UTC
Labels: bug
